# E represents energy (measured in Joules)
# m represents mass (measured in kilograms)
# c represents the speed of light (measured approximately as 300000000 meters per second)
m = int(input("m: "))
E = m * (pow(300000000, 2))
print(f"E: {E}")
